### ISSUE TITLE
What are we doing and why?

### ISSUE THREAD

**Issue by EFT-Defra** [Defra-Data-Science-Centre-of-Excellence/sds-data-model#130]

**Comment by s-flint-defra** [comment]
This issue is quite vague. Suggest that what we are doing will be covered off should the next two sprints be successful (public docstrings, documentation etc.) @jpd-defra ? 

Why we are doing it is perhaps simpler, but might need to be thrashed out across the workstreams. @jpd-defra @EFT-Defra would the away day be a good opportunity to have a team discussion on this?

**Comment by jpd-defra** [comment]
> This issue is quite vague. Suggest that what we are doing will be covered off should the next two sprints be successful (public docstrings, documentation etc.) @jpd-defra ?
> 
> Why we are doing it is perhaps simpler, but might need to be thrashed out across the workstreams. @jpd-defra @EFT-Defra would the away day be a good opportunity to have a team discussion on this?

I think this can be closed. The work we are doing to tidy up, and some of the slides I made recently get this down in writing.
