### ISSUE TITLE
Categorize Doesn't Appear to Respect Lookups

### ISSUE THREAD

**Issue by danlewis85** [Defra-Data-Science-Centre-of-Excellence/sds-data-model#206]
I can't seem to get the alpha 2 release of the data model to create a categorical output that references a lookup.

I have two issues that may be a factor, but I've not been able to resolve:

1. How to define the lookup.

It's not clear to me whether the lookup should be defined like this:
`lookup = {17:'Deep Peaty Soils', 97:'Shallow Peaty Soils', 159:'Soils with Peaty Pockets'}`
or, like this:
`lookup = {'Deep Peaty Soils': 17, 'Shallow Peaty Soils': 97, 'Soils with Peaty Pockets': 159}`

Regardless, the outcome always seems to be coded:
`{'Deep Peaty Soils': 0, 'Shallow Peaty Soils': 1, 'Soils with Peaty Pockets': 2, 'NoData': 255}`

It was only when I tried to set arbitrary category codes that it was obvious that the model didn't seem to be respecting what was in the lookup.

2. Where to place the lookup.

There are two spots where a lookup could be provided - in the constructor, and in the categorize method. It is not clear whether I should prefer one or the other.

Here is some example code:
```
(DataFrameWrapper
    .from_files(
        data_path = "/dbfs/mnt/base/unrestricted/source_defra_data_services_platform/dataset_peaty_soils/format_GPKG_peaty_soils/LATEST_peaty_soils/refdata_owner.peaty_soils_location.gpkg",
        metadata_path = 'https://www.data.gov.uk/api/2/rest/harvestobject/c3732e82-f21d-4e26-b410-3020c9fea1cb/xml',
        name = "Peaty Soils Location",
        lookup=lookup) # <-- lookup goes here?
    .call_method("withColumnRenamed", **{'existing':"wkb_geometry", 'new':"geometry"})
    .call_method("select", [col("pclassdesc"), col("geometry")])
    .categorize(['pclassdesc'], lookup) # <-- and/or lookup goes here?
    .index()
    .to_zarr(
        path="/dbfs/mnt/lab/unrestricted/daniel.lewis@defra.gov.uk/peaty_soil_location_cat.zarr",
        columns=["pclassdesc"])
)
```

**Comment by jamesgyoung** [comment]
Attribute `lookup` of the `DataFrameWrapper` class exists mainly as a space for `categorize` to pass a lookup (generated or provided to it) to `to_zarr` so that it can be written to the output dataset.

The functionality of `categorize` is to map onto the columns provided of the `.data` attribute of the `DataFrameWrapper` an optionally auto generated lookup of `{"category_value": numeric_representation}` or a user provided lookup in the same format. This happens inplace, i.e. calling `.categorize(columns=["my_col"])` will map a lookup and change the values for that column in the `.data` attribute. This lookup though is added to the `.lookup` attribute of the same `DataFrameWrapper`.

---

A bug was likely encountered here though where `categorize` was called multiple times on the same column which left the underlying values in `.data` as null.

---

Additionally `NoData` should be written as `nodata`.

**Comment by jamesgyoung** [comment]
To mitigate the problem calling categorize twice on the same column causes, instead of changing in place the `.data` spark dataframe, a different object could be used.

This will not be addressed for now.
