### ISSUE TITLE
Encode categorical variables before rasterisation

### ISSUE THREAD

**Issue by TimAshelford** [Defra-Data-Science-Centre-of-Excellence/sds-data-model#33]
I wonder whether `pandas.Categorical()` might provide an easy way into this problem.

**Comment by EFT-Defra** [comment]
Hi @s-flint-defra and @lara56,

To reiterate what we just discussed, the idea here is to convert specified string variables to categorical variables so that they can be rasterised as appropriately-sized integer arrays while preserving the mapping of categories to codes in some way.

For example, upon the completion of this task, the following would return a [`xarray.Dataset`](https://xarray.pydata.org/en/stable/user-guide/data-structures.html#dataset) of 3 [`xarray.DataArray`](https://xarray.pydata.org/en/stable/user-guide/data-structures.html#dataarray)s where `CTRY21NM` and `CTRY21NMW` are both integer DataArrays. Ideally, the mapping of categories to codes would be stored in the [`coords`](https://xarray.pydata.org/en/stable/user-guide/data-structures.html#dataarray-coordinates) property each, which would then allow indexing by the original category.   

```python
from sds_data_model.vector import VectorLayer

ctry = (
    VectorLayer.from_files(
        data_path = "Countries_(December_2021)_GB_BUC/CTRY_DEC_2021_GB_BUC.shp",
        convert_to_categorical = ["CTRY21NM", "CTRY21NMW"]
        name = "ctry",    
    )
   .to_tiles()
   .to_dataset_as_raster(
        columns = ["CTRY21NM", "CTRY21NMW", "Shape__Area"]
    )
)
```
Your approach should also be able to be applied to each `VectorTile` when `TiledVectorLayer.from_files` is called.
