### ISSUE TITLE
Get CRS + datatype information for whole dataset

### ISSUE THREAD

**Issue by EFT-Defra** [Defra-Data-Science-Centre-of-Excellence/sds-data-model#40]
Hi @jpd-defra and @JamesKeny0n,

There are two issues here:

1. We want to ensure that a TiledVectorLayer can only be constructed from a BNG vector file
2. We want to get the data type of each field (without having to loop through the entire collection of tiles) so that we can use it when we rasterise a field

The obvious answer to these issues is using the [Python GDAL bindings](https://gdal.org/python/) to get that information from the layer before reading it into tiles.

Getting the project is relatively easy:

```python
from osgeo.ogr import Open

data_source = Open("/path/to/data_source")
layer = data_source.GetLayer("layer_name")
spatial_reference = layer.GetSpatialRef()
```

Getting the data type of each column is only a little bit trickery and you could use the approach I did in [`pyspark-vector-files._schema`](https://github.com/Defra-Data-Science-Centre-of-Excellence/pyspark-vector-files/blob/6dd5483ab1441d9288e6d2e3bb660ff0140f7bdb/src/pyspark_vector_files/_schema.py#L29-L45). You then need to map those datatypes to their corresponding `numpy` data types.  I've got a mapping of OGR-to-Spark data types then Spark-to-Pandas data types in [`pyspark-vector-files`](https://github.com/Defra-Data-Science-Centre-of-Excellence/pyspark-vector-files/blob/6dd5483ab1441d9288e6d2e3bb660ff0140f7bdb/src/pyspark_vector_files/__init__.py#L220-L251) but I think the post @jpd-defra found is probably a better starting point.

 I thought you'd be able to pass a dictionary of column names and data types to [`geopandas.read_file`](https://geopandas.org/en/stable/docs/reference/api/geopandas.read_file.html) or on to [`fiona.open`](https://fiona.readthedocs.io/en/latest/fiona.html#fiona.open) but it doesn't seem possible, so you may have to explicitly set them after the `geopandas.read_file` all in [`_vector._from_file`](https://github.com/Defra-Data-Science-Centre-of-Excellence/sds-data-model/blob/370083696c3678ed625abe22d8ea031e7f4ee613/src/sds_data_model/_vector.py#L31-L42).

You will also need some way of storing this type information can you can use it [`TiledVectorLayer.to_dataset_as_raster`](https://github.com/Defra-Data-Science-Centre-of-Excellence/sds-data-model/blob/370083696c3678ed625abe22d8ea031e7f4ee613/src/sds_data_model/vector.py#L259-L304) in place of the previous approach.

It might also be worth look at the approach taken in [`pyogrio.read_info`](https://github.com/geopandas/pyogrio/blob/0b8758b5434a95ad921e22e6431ada05a5f1a2e1/pyogrio/core.py#L142-L179)

**Comment by jpd-defra** [comment]
Potentially useful resources:
https://gis.stackexchange.com/questions/18715/mapping-between-ogr-and-python-data-types
https://pcjericks.github.io/py-gdalogr-cookbook/vector_layers.html#get-shapefile-fields-and-types-get-the-user-defined-fields

**Comment by jamesgyoung** [comment]
@EFT-Defra, @jpd-defra 

## GDAL/pyogrio

- pyogrio's [`read_info` function](https://github.com/geopandas/pyogrio/blob/33a420dc6717886967fd8ebf6d50a1d52abbf570/pyogrio/core.py#L142-L179) calls the function [`ogr_read_info`](https://github.com/geopandas/pyogrio/blob/0b8758b5434a95ad921e22e6431ada05a5f1a2e1/pyogrio/_io.pyx#L970#L1012). This function retrieves data types or fields from a layer calling the cython function [`get_fields`](https://github.com/geopandas/pyogrio/blob/0b8758b5434a95ad921e22e6431ada05a5f1a2e1/pyogrio/_io.pyx#L306-L379)
- This `get_fields` function utilises GDAL and a [dtype lookup](https://github.com/geopandas/pyogrio/blob/0b8758b5434a95ad921e22e6431ada05a5f1a2e1/pyogrio/_io.pyx#L33#L84) that maps "OGR integer field types to Python field type names" that can be used by a GeoDataFrame.
-  The function (approximately) in python for our use case is:
```python
from osgeo.ogr import OFSTNone, OFSTBoolean, OFSTInt16, OFSTFloat32, Open
from numpy import empty, ndarray

FIELD_TYPES = [
    'int32',         # OFTInteger, Simple 32bit integer
    None,            # OFTIntegerList, List of 32bit integers, not supported
    'float64',       # OFTReal, Double Precision floating point
    None,            # OFTRealList, List of doubles, not supported
    'object',        # OFTString, String of UTF-8 chars
    None,            # OFTStringList, Array of strings, not supported
    None,            # OFTWideString, deprecated, not supported
    None,            # OFTWideStringList, deprecated, not supported
    'object',        # OFTBinary, Raw Binary data
    'datetime64[D]', # OFTDate, Date
    None,            # OFTTime, Time, NOTE: not directly supported in numpy
    'datetime64[ms]',# OFTDateTime, Date and Time
    'int64',         # OFTInteger64, Single 64bit integer
    None             # OFTInteger64List, List of 64bit integers, not supported
]


FIELD_SUBTYPES = {
    OFSTNone: None,           # No subtype
    OFSTBoolean: "bool",      # Boolean integer
    OFSTInt16: "int16",       # Signed 16-bit integer
    OFSTFloat32: "float32",   # Single precision (32 bit) floating point
}

def get_fields(data_path: str, **data_kwargs) -> ndarray:
    if "layer" in data_kwargs:
        iLayer = data_kwargs.get("layer")
    else:
        iLayer = 0
        
    data_source = Open(data_path)
    ogr_layer = data_source.GetLayer(iLayer=iLayer)
    layer_definition = ogr_layer.GetLayerDefn()
    field_count = layer_definition.GetFieldCount()

    fields = empty(shape=(field_count, 4), dtype=object)
    fields_view = fields[:,:]

    for i in range(field_count):

        ogr_fielddef = layer_definition.GetFieldDefn(i)

        field_name = ogr_fielddef.GetName()

        field_type = ogr_fielddef.GetType()

        np_type = FIELD_TYPES[field_type]

        field_subtype = ogr_fielddef.GetSubType()
        subtype = FIELD_SUBTYPES.get(field_subtype)

        if subtype is not None:
            # bool, int16, float32 dtypes
            np_type = subtype

        fields_view[i,0] = i
        fields_view[i,1] = field_type
        fields_view[i,2] = field_name
        fields_view[i,3] = np_type

    return fields
```
Some object dtypes in the lookup may need to be remapped.

The function returns an array of rows for each field featuring:
-  column index position
- field type (gdal type code that corresponds to type)
- column name 
- numpy column type 
e.g. :
```python
get_fields("qgis_dummy.gpkg")
array([[0, 0, 'whole_number_integer', 'int32'],
       [1, 12, 'whole_number_integer_64bit', 'int64'],
       [2, 2, 'decimal_number', 'float64'],
       [3, 4, 'text_string', 'object'],
       [4, 4, 'json_string', 'object'],
       [5, 9, 'date', 'datetime64[D]'],
       [6, 11, 'date_and_time', 'datetime64[ms]'],
       [7, 8, 'binary_object_blob', 'object'],
       [8, 1, 'boolean', 'bool']], dtype=object)
```

In the `ogr_read_info` function, only the column name (`fields[:,2]`) and numpy type (`fields[:,3]`) are used, likely similar to our use case. We can remove the other info returned if unnecessary.

It would be better to incorporate the original [`get_fields`](https://github.com/geopandas/pyogrio/blob/0b8758b5434a95ad921e22e6431ada05a5f1a2e1/pyogrio/_io.pyx#L306-L379) function from pyogrio if that is something we decide to do.

---

## Issue with this method

- The main issue for our use case is the function does not provide the minimum data type for a column. It reads the schema of the input file to get the datatype. Sometimes this will be accurate but there will also be occasions where it isn't, as well as impossible in the case of unsigned types which are not supported by OGR (also [GeoPackage spec](https://www.geopackage.org/spec/)/SQLite). 
- This is exacerbated by datasets written from GeoPandas (using fiona by default), where the schema is auto generated from the function [`infer_schema`](https://github.com/geopandas/geopandas/blob/28462f8e7fd893e01be52f444e142a1a00c36f8e/geopandas/io/file.py#L574-L616). 
- The types for that schema are produced by an internal function [`convert_type`](https://github.com/geopandas/geopandas/blob/f01bcedf72d6a89a5c2f71b782db660c4ac5a414/geopandas/io/file.py#L580-L592). This function takes the column data type (called via `dataframe.dtypes`) and conditionally converts it to a python type (of type string). Generally numeric types will be passed to the code `type(np.zeros(1, in_type).item()).__name__`. This reduces uints, ints and floats of all bit variations to "int" and "float" which are then mapped to Fiona's types (this mapping can be viewed with `fiona.FIELD_TYPES_MAP.`). This aggregation causes data to be written to GeoPackage using `INTEGER` and `REAL`, even though smaller GDAL and SQLite types are available.).
- One method for dealing with this issue is using pyogrio's `write_dataframe` and `read_dataframe` functions. They take ([almost](https://github.com/geopandas/pyogrio/issues/17)) full advantage of the available GDAL types and have mappings to numpy. 
- These functions will respect writing and reading of float32 as well as int16 & int32. float16 and int8 do not have an equivalent gdal types (even though int8 is supported in gpkg). pyogrio will cast an int8(/uint8) column to int16 when writing to file. It will not however allow writing of float16 columns - throws an error - they must be cast before hand.
- To read data into the data model with the minimum data type (supported and written to file) we might want to change the reading of data from using fiona to pyogrio using `engine="pyogrio"` in the `read_file` function where it currently appears in data-model code. We would need to update to version 0.11 of geopandas [where this functionality was added](https://geopandas.org/en/stable/docs/changelog.html).
- This writing/reading does not provide us with the absolute minimum type. We would still need to check integer columns **only** if we assumed float columns were correctly written. This is **not** a safe assumption.
- After reviewing this information I think we should integrate and use pyogrio's `read_info` function to read dtypes. It is directly calling OGR. We do not obtain any advantage (beyond controlling the dtype mapping) from reimplementing it in OGR. We could write separate logic to handle object columns. This function could also be used to read CRS depending on our preferences.

## Parquet
- Issue #22 aims to add parquet support . 
- Parquet does [support unsigned types](https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#unsigned-integers). Parquet therefore holds the potential to natively support the minimum data type without having to do further checking.
- GDAL has a new [(Geo)Arrow driver](https://gdal.org/drivers/vector/arrow.html) although GDAL has to be built from source with the arrow option enabled (and pointing to Arrow) to get access to it. This likely has the ability to read dtypes and CRS however if the driver/GDAL is mapping parquet types to OGR types, I'm not certain it will be able to read minimum types, instead the types will be at the OGR aggregation, requiring min_type checking.
- This GDAL driver is [slow at reading data](https://github.com/geopandas/geopandas/issues/2429#issuecomment-1126077276) compared to geopandas/pyarrow.
- The schema of parquet files can be read using pyarrow (`pyarrow.parquet.read_schema("file.parquet")`), this doesn't read the CRS though. 
- CRS metadata is not (binary) encoded within parquet files and could be directly lifted. I'm unsure how `geopandas.read_parquet` reads CRS but the method could be extracted and tested (to try and avoid reading the entire file to get this info).

My point is:
- with an Arrow-driver enabled GDAL, pyogrio can support the reading of metadata for parquet, but the data types it provides could be incorrect (compared to the assumed continued use of geopandas.read_parquet for speed) due to ogr dtype aggregation/mapping. I have not tested this, I couldn't build GDAL with Arrow enable although it is possible - [CMake build hints - Arrow](https://gdal.org/build_hints.html#arrow).
- If we wish to use the dtypes parquet supports pyarrow is the best method. CRS is not impossible and GDAL is available for this use if need be.
- The goal here is trying to avoid looping through all data values to obtain a minimum type. The caveat of this being, parquet can be written using types that are not the minimum. If we have fast min_dtype checking even on large datasets this becomes a non-issue.



---

### Precision
- Because most libraries (including) GDAL do not support float16 and it's use is highly specific it's not worth assigning or checking.
- That leaves float32 and float64. The range of float32 is large meaning if we were to continue using rasterio's min dtype checker we will likely always return float32 for float columns. The precision of float32 is 6. This is reasonably large meaning in almost all cases float64 isn't necessary. Where it is, it's easier to just allow the manual passing of a schema or disbale min dtype checking instead of trying to measure precision.
- I do have a function that works for a checking precision, but I think it's now unecessary.
